---
# aws-amzn-playbook.yml
- name: 'Provision AWS Amazon Linux 2 Machine'
  hosts: all
  remote_user: ec2-user
  become_method: sudo
  become: true

  tasks:
  - name: install Apache
    yum:
      name: 'httpd'
      state: present
